"""
Storage service for supplier PDFs.

- Invoice PDFs → Cloudinary (dazz-suppliers/invoices/) — authenticated access
- Bank certificates → Cloudflare R2 (bank-certs/) — signed URLs 15min

Cloudinary credentials reuse the existing project config (CLOUDINARY_CLOUD_NAME, etc.).
R2 credentials: R2_ACCOUNT_ID, R2_ACCESS_KEY_ID, R2_SECRET_ACCESS_KEY, R2_BUCKET_NAME, R2_ENDPOINT.
"""

import os
import uuid
import shutil
from datetime import datetime, timezone
from typing import Optional

from app.services.validators import sanitize_filename

import cloudinary
import cloudinary.uploader
import cloudinary.utils
import boto3
from botocore.config import Config as BotoConfig
from fastapi import UploadFile

# ============================================
# LOCAL FALLBACK (for temp files before upload)
# ============================================

UPLOAD_DIR = os.path.join("uploads", "suppliers")
os.makedirs(UPLOAD_DIR, exist_ok=True)

# ============================================
# CLOUDINARY — Invoice PDFs
# ============================================
# Config is already loaded globally by cloudinary_service.py at startup.
# We just use cloudinary.uploader directly.

CLOUDINARY_FOLDER = "dazz-suppliers/invoices"
INVOICE_SIGNED_URL_EXPIRY = 900  # 15 minutes — same as bank certs


def save_invoice_pdf(file: UploadFile, supplier_id: int, contents: bytes = None) -> str:
    """
    Upload supplier invoice PDF to Cloudinary with authenticated access.

    Stored in dazz-suppliers/invoices/{supplier_id}/
    Uses resource_type=raw, access_mode=authenticated (no public URL).
    Access only via signed URLs generated by get_invoice_pdf_url().

    Args:
        file: FastAPI UploadFile (PDF)
        supplier_id: Supplier ID for folder organization
        contents: Pre-read bytes (avoids consuming file stream twice)

    Returns:
        Cloudinary public_id (NOT a URL — use get_invoice_pdf_url() for signed access)
    """
    timestamp = datetime.now(timezone.utc).strftime("%Y%m%d%H%M%S")
    short_id = uuid.uuid4().hex[:8]
    clean_name = os.path.splitext(sanitize_filename(file.filename or "invoice"))[0][:40]
    public_id = f"{CLOUDINARY_FOLDER}/{supplier_id}/{clean_name}_{timestamp}_{short_id}"

    # Save to temp file first (Cloudinary needs a file path or bytes)
    temp_path = os.path.join(UPLOAD_DIR, f"tmp_{short_id}.pdf")
    try:
        with open(temp_path, "wb") as out:
            if contents:
                out.write(contents)
            else:
                shutil.copyfileobj(file.file, out)

        result = cloudinary.uploader.upload(
            temp_path,
            public_id=public_id,
            resource_type="raw",
            type="authenticated",
            overwrite=False,
        )

        # Return public_id — the caller must use get_invoice_pdf_url() to access it
        returned_id = result.get("public_id", public_id)
        print(f"Cloudinary upload OK (authenticated): {returned_id}")
        return returned_id

    finally:
        if os.path.exists(temp_path):
            os.remove(temp_path)


def get_invoice_pdf_url(public_id: str) -> str:
    """
    Generate a signed URL for a supplier invoice PDF (15min expiry).

    Invoices contain NIF/IBAN — no permanent public URLs allowed.

    Args:
        public_id: Cloudinary public_id returned by save_invoice_pdf()

    Returns:
        Signed URL valid for 15 minutes
    """
    # cloudinary.utils.cloudinary_url with sign_url=True and type=authenticated
    url, _ = cloudinary.utils.cloudinary_url(
        public_id,
        resource_type="raw",
        type="authenticated",
        sign_url=True,
        secure=True,
    )
    return url


def delete_invoice_pdf(public_id: str) -> bool:
    """Delete an invoice PDF from Cloudinary by its public_id."""
    if not public_id:
        return False

    try:
        cloudinary.uploader.destroy(public_id, resource_type="raw", type="authenticated")
        print(f"Cloudinary delete OK: {public_id}")
        return True
    except Exception as e:
        print(f"Cloudinary delete error: {e}")
        return False


def _extract_cloudinary_public_id(url: str) -> Optional[str]:
    """Extract public_id from a Cloudinary raw URL.

    URL format: .../raw/upload/v12345/folder/file.pdf
    We need to find 'upload', skip the version, and return the rest.
    """
    try:
        parts = url.split("/")
        upload_idx = -1
        for i, part in enumerate(parts):
            if part == "upload":
                upload_idx = i
                break
        if upload_idx == -1:
            return None
        # Skip version (v12345)
        path_parts = parts[upload_idx + 2:]
        return "/".join(path_parts)
    except Exception:
        return None


# ============================================
# CLOUDFLARE R2 — Bank Certificates
# ============================================

R2_ACCOUNT_ID = os.getenv("R2_ACCOUNT_ID", "")
R2_ACCESS_KEY_ID = os.getenv("R2_ACCESS_KEY_ID", "")
R2_SECRET_ACCESS_KEY = os.getenv("R2_SECRET_ACCESS_KEY", "")
R2_BUCKET_NAME = os.getenv("R2_BUCKET_NAME", "bank-certs")
R2_ENDPOINT = os.getenv("R2_ENDPOINT", "")

SIGNED_URL_EXPIRY = 900  # 15 minutes (RGPD requirement)


def _get_r2_client():
    """Create boto3 S3 client configured for Cloudflare R2."""
    if not all([R2_ENDPOINT, R2_ACCESS_KEY_ID, R2_SECRET_ACCESS_KEY]):
        raise RuntimeError(
            "R2 credentials not configured. "
            "Set R2_ENDPOINT, R2_ACCESS_KEY_ID, R2_SECRET_ACCESS_KEY."
        )

    return boto3.client(
        "s3",
        endpoint_url=R2_ENDPOINT,
        aws_access_key_id=R2_ACCESS_KEY_ID,
        aws_secret_access_key=R2_SECRET_ACCESS_KEY,
        config=BotoConfig(
            signature_version="s3v4",
            region_name="auto",
        ),
    )


def save_bank_cert(file: UploadFile, supplier_id: int, contents: bytes = None) -> str:
    """
    Upload bank certificate PDF to Cloudflare R2.

    Stored in bank-certs/{supplier_id}/ — never publicly accessible.
    Access only via signed URLs with 15min expiry.

    Args:
        file: FastAPI UploadFile (PDF)
        supplier_id: Supplier ID
        contents: Pre-read bytes (avoids consuming file stream twice)

    Returns:
        R2 object key (NOT a public URL — use get_bank_cert_url to get signed URL)
    """
    short_id = uuid.uuid4().hex[:8]
    object_key = f"bank-certs/{supplier_id}/cert_{short_id}.pdf"

    temp_path = os.path.join(UPLOAD_DIR, f"tmp_bank_{short_id}.pdf")
    try:
        with open(temp_path, "wb") as out:
            if contents:
                out.write(contents)
            else:
                shutil.copyfileobj(file.file, out)

        client = _get_r2_client()
        client.upload_file(
            temp_path,
            R2_BUCKET_NAME,
            object_key,
            ExtraArgs={"ContentType": "application/pdf"},
        )

        print(f"R2 upload OK: {object_key}")
        return object_key

    finally:
        if os.path.exists(temp_path):
            os.remove(temp_path)


def get_bank_cert_url(object_key: str) -> str:
    """
    Generate a signed URL for a bank certificate (15min expiry).

    This is the ONLY way to access bank certs — no permanent public URLs.
    Each call generates a fresh URL that expires in 15 minutes.

    Args:
        object_key: R2 object key returned by save_bank_cert()

    Returns:
        Pre-signed URL valid for 15 minutes
    """
    client = _get_r2_client()
    url = client.generate_presigned_url(
        "get_object",
        Params={
            "Bucket": R2_BUCKET_NAME,
            "Key": object_key,
        },
        ExpiresIn=SIGNED_URL_EXPIRY,
    )
    return url


def delete_bank_cert(object_key: str) -> bool:
    """Delete a bank certificate from R2."""
    try:
        client = _get_r2_client()
        client.delete_object(Bucket=R2_BUCKET_NAME, Key=object_key)
        print(f"R2 delete OK: {object_key}")
        return True
    except Exception as e:
        print(f"R2 delete error: {e}")
        return False
